language: objective-c
osx_image: xcode10.0

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/Library/Caches/Homebrew"
    - vendor/bundle

before_install:
  - brew bundle

install:
  - bundle install --deployment --jobs 4

script:
  - ./Resources/scripts/validate_carthage.sh
  - ./Resources/scripts/validate_cocoapods.sh
  - bundle exec fastlane test

after_success:
    # - ./Resources/scripts/publish_docs.sh
