# Opt out of sending usage stats
opt_out_usage

#######################################################################
# Project specific variables
#######################################################################

PROJECT_FILE = "CoreDataStack.xcodeproj".freeze

TVOS_SCHEME = "CoreDataStackTV".freeze
MACOS_SCHEME = "CoreDataStackOSX".freeze
IOS_SCHEME = "CoreDataStack".freeze


#######################################################################
# Lifecycle Hooks
#######################################################################
  
before_all do
end

after_all do |lane|
    # This block is called, only if the executed lane was successful
end

error do |lane, exception|
end

#######################################################################
# Test Lanes
#######################################################################

desc "Runs all the tests"
lane :test do
    # tvOS and iOS
    [TVOS_SCHEME, IOS_SCHEME].each { |scheme|
        scan(scheme: scheme)
    }

    # macOS
    scan(scheme: MACOS_SCHEME, destination: "platform=macOS,arch=x86_64")
end
